/**
 * Created by Denis on 23.04.2018.
 */
//authority
export const LOAD_START_AUTH = "LOAD_START_AUTH";
export const LOAD_END_AUTH = "LOAD_END_AUTH";
export const LOAD_ERROR_AUTH = "LOAD_ERROR_AUTH";

//hero
export const LOAD_START_HERO_FULL = "LOAD_START_HERO_FULL";
export const LOAD_END_HERO_FULL = "LOAD_END_HERO_FULL";
export const LOAD_ERROR_HERO_FULL = "LOAD_ERROR_HERO_FULL";

export const LOAD_END_DICTIONARY = "LOAD_END_DICTIONARY";

export const CHANGE_LITE_MODE = "CHANGE_LITE_MODE";

export const LOAD_START_MATCHUP_ONEHERO = "LOAD_START_MATCHUP_ONEHERO";
export const LOAD_END_MATCHUP_ONEHERO = "LOAD_END_MATCHUP_ONEHERO";
export const LOAD_ERROR_MATCHUP_ONEHERO = "LOAD_ERROR_MATCHUP_ONEHERO";

export const LOAD_START_STATISTIC_ONEHERO = "LOAD_START_STATISTIC_ONEHERO";
export const LOAD_END_STATISTIC_ONEHERO = "LOAD_END_STATISTIC_ONEHERO";
export const LOAD_ERROR_STATISTIC_ONEHERO = "LOAD_ERROR_STATISTIC_ONEHERO";